"""add starts_at, ends_at, and achieved_at to objectives and key_results

Revision ID: 20200921152000
Revises: 20200914152057
Create Date: 2020-09-21 15:20:03.163078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20200921152000"
down_revision = "20200914152057"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("key_results", sa.Column("achieved_at", sa.DateTime(), nullable=True))
    op.add_column("key_results", sa.Column("ends_at", sa.DateTime(), nullable=True))
    op.add_column("key_results", sa.Column("starts_at", sa.DateTime(), nullable=True))
    op.add_column("objectives", sa.Column("achieved_at", sa.DateTime(), nullable=True))
    op.add_column("objectives", sa.Column("ends_at", sa.DateTime(), nullable=True))
    op.add_column("objectives", sa.Column("starts_at", sa.DateTime(), nullable=True))
    op.drop_column("objectives", "target_date")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "objectives",
        sa.Column(
            "target_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("objectives", "starts_at")
    op.drop_column("objectives", "ends_at")
    op.drop_column("objectives", "achieved_at")
    op.drop_column("key_results", "starts_at")
    op.drop_column("key_results", "ends_at")
    op.drop_column("key_results", "achieved_at")
    # ### end Alembic commands ###
