"""measured_at is required and unique

Revision ID: 20201118112710
Revises: 20201118112110
Create Date: 2020-11-18 11:27:11.785576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20201118112710"
down_revision = "20201118112110"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "progress_points", "measured_at", existing_type=sa.DATE(), nullable=False
    )
    op.create_unique_constraint(
        "uq_key_result_id_measured_at",
        "progress_points",
        ["key_result_id", "measured_at"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_key_result_id_measured_at", "progress_points", type_="unique"
    )
    op.alter_column(
        "progress_points", "measured_at", existing_type=sa.DATE(), nullable=True
    )
    # ### end Alembic commands ###
