"""objectives belong to work item containers

Revision ID: 20201020150945
Revises: 20201012223141
Create Date: 2020-10-20 15:09:46.627927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20201020150945"
down_revision = "20201012223141"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "objectives",
        sa.Column("work_item_container_id", sa.BigInteger(), nullable=True),
    )
    op.create_index(
        op.f("ix_objectives_work_item_container_id"),
        "objectives",
        ["work_item_container_id"],
        unique=False,
    )
    op.drop_index("ix_objectives_space_id", table_name="objectives")
    op.drop_constraint("objectives_space_id_fkey", "objectives", type_="foreignkey")
    op.create_foreign_key(
        "fk_objectives_work_item_container_id",
        "objectives",
        "work_item_containers",
        ["work_item_container_id"],
        ["id"],
    )
    op.drop_column("objectives", "space_id")
    op.drop_column("space_work_item_container_mappings", "is_primary")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "space_work_item_container_mappings",
        sa.Column("is_primary", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "objectives",
        sa.Column("space_id", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        "fk_objectives_work_item_container_id", "objectives", type_="foreignkey"
    )
    op.create_foreign_key(
        "objectives_space_id_fkey", "objectives", "spaces", ["space_id"], ["id"]
    )
    op.create_index("ix_objectives_space_id", "objectives", ["space_id"], unique=False)
    op.drop_index(op.f("ix_objectives_work_item_container_id"), table_name="objectives")
    op.drop_column("objectives", "work_item_container_id")
    # ### end Alembic commands ###
