"""break out polymorphic columns

Revision ID: 20201006134829
Revises: 20201001154838
Create Date: 2020-10-06 13:48:30.595082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20201006134829"
down_revision = "20201001154838"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "progress_points", sa.Column("key_result_id", sa.BigInteger(), nullable=True)
    )
    op.add_column(
        "progress_points", sa.Column("objective_id", sa.BigInteger(), nullable=True)
    )
    op.create_index(
        op.f("ix_progress_points_key_result_id"),
        "progress_points",
        ["key_result_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_progress_points_objective_id"),
        "progress_points",
        ["objective_id"],
        unique=False,
    )
    op.drop_index("ix_progress_points_trackable_id", table_name="progress_points")
    op.create_foreign_key(
        None, "progress_points", "objectives", ["objective_id"], ["id"]
    )
    op.create_foreign_key(
        None, "progress_points", "key_results", ["key_result_id"], ["id"]
    )
    op.drop_column("progress_points", "trackable_type")
    op.drop_column("progress_points", "trackable_id")
    op.create_index(
        op.f("ix_work_item_containers_containable_type"),
        "work_item_containers",
        ["containable_type", "containable_id"],
        unique=False,
    )
    op.alter_column(
        "work_items", "workable_id", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "work_items", "workable_type", existing_type=sa.VARCHAR(), nullable=True
    )
    op.create_index(
        op.f("ix_work_items_workable_type"),
        "work_items",
        ["workable_type", "workable_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_work_items_workable_type"), table_name="work_items")
    op.alter_column(
        "work_items", "workable_type", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "work_items", "workable_id", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_index(
        op.f("ix_work_item_containers_containable_type"),
        table_name="work_item_containers",
    )
    op.add_column(
        "progress_points",
        sa.Column("trackable_id", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "progress_points",
        sa.Column("trackable_type", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_index(
        "ix_progress_points_trackable_id",
        "progress_points",
        ["trackable_id", "trackable_type"],
        unique=False,
    )
    op.drop_index(op.f("ix_progress_points_objective_id"), table_name="progress_points")
    op.drop_index(
        op.f("ix_progress_points_key_result_id"), table_name="progress_points"
    )
    op.drop_column("progress_points", "objective_id")
    op.drop_column("progress_points", "key_result_id")
    # ### end Alembic commands ###
