"""Initial database setup

Revision ID: 20200826150422
Revises: 
Create Date: 2020-08-26 15:04:23.793492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20200826150422"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spaces",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "work_item_containers",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("containable_type", sa.String(), nullable=False),
        sa.Column("containable_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "objectives",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("target_date", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("space_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_objectives_space_id"), "objectives", ["space_id"], unique=False
    )
    op.create_table(
        "space_work_item_container_mappings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("space_id", sa.BigInteger(), nullable=False),
        sa.Column("work_item_container_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_item_container_id"],
            ["work_item_containers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_space_work_item_container_mappings_space_id"),
        "space_work_item_container_mappings",
        ["space_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_space_work_item_container_mappings_work_item_container_id"),
        "space_work_item_container_mappings",
        ["work_item_container_id"],
        unique=False,
    )
    op.create_table(
        "work_items",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("workable_type", sa.String(), nullable=False),
        sa.Column("workable_id", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("work_item_container_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["work_item_container_id"],
            ["work_item_containers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_work_items_work_item_container_id"),
        "work_items",
        ["work_item_container_id"],
        unique=False,
    )
    op.create_table(
        "key_results",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("starting_value", sa.Float(), nullable=True),
        sa.Column("target_value", sa.Float(), nullable=True),
        sa.Column("value_type", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("objective_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["objective_id"],
            ["objectives.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_key_results_objective_id"),
        "key_results",
        ["objective_id"],
        unique=False,
    )
    op.create_table(
        "key_result_progress_points",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("key_result_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["key_result_id"],
            ["key_results.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_key_result_progress_points_key_result_id"),
        "key_result_progress_points",
        ["key_result_id"],
        unique=False,
    )
    op.create_table(
        "key_result_work_item_mappings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("key_result_id", sa.BigInteger(), nullable=False),
        sa.Column("work_item_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["key_result_id"],
            ["key_results.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_key_result_work_item_mappings_key_result_id"),
        "key_result_work_item_mappings",
        ["key_result_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_key_result_work_item_mappings_work_item_id"),
        "key_result_work_item_mappings",
        ["work_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_key_result_work_item_mappings_work_item_id"),
        table_name="key_result_work_item_mappings",
    )
    op.drop_index(
        op.f("ix_key_result_work_item_mappings_key_result_id"),
        table_name="key_result_work_item_mappings",
    )
    op.drop_table("key_result_work_item_mappings")
    op.drop_index(
        op.f("ix_key_result_progress_points_key_result_id"),
        table_name="key_result_progress_points",
    )
    op.drop_table("key_result_progress_points")
    op.drop_index(op.f("ix_key_results_objective_id"), table_name="key_results")
    op.drop_table("key_results")
    op.drop_index(op.f("ix_work_items_work_item_container_id"), table_name="work_items")
    op.drop_table("work_items")
    op.drop_index(
        op.f("ix_space_work_item_container_mappings_work_item_container_id"),
        table_name="space_work_item_container_mappings",
    )
    op.drop_index(
        op.f("ix_space_work_item_container_mappings_space_id"),
        table_name="space_work_item_container_mappings",
    )
    op.drop_table("space_work_item_container_mappings")
    op.drop_index(op.f("ix_objectives_space_id"), table_name="objectives")
    op.drop_table("objectives")
    op.drop_table("work_item_containers")
    op.drop_table("spaces")
    # ### end Alembic commands ###
