"""add progress_percentages and default values

Revision ID: 20201022150728
Revises: 20201021161251
Create Date: 2020-10-22 15:07:30.482748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20201022150728"
down_revision = "20201021161251"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "key_results",
        sa.Column(
            "progress_percentage", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "objectives",
        sa.Column(
            "progress_percentage", sa.Integer(), nullable=False, server_default="0"
        ),
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("objectives", "progress_percentage")
    op.drop_column("key_results", "progress_percentage")
    # ### end Alembic commands ###
