"""eliminating requirement for work_item_container on work item

Revision ID: 20201119125408
Revises: 20201118112710
Create Date: 2020-11-19 12:54:09.258036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20201119125408"
down_revision = "20201118112710"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "work_items", "work_item_container_id", existing_type=sa.BIGINT(), nullable=True
    )
    op.alter_column(
        "work_items", "workable_id", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "work_items", "workable_type", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "work_items", "workable_type", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "work_items", "workable_id", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "work_items",
        "work_item_container_id",
        existing_type=sa.BIGINT(),
        nullable=False,
    )
    # ### end Alembic commands ###
