"""add is_primary and unique index to space_work_item_container_mappings

Revision ID: 20201009093245
Revises: 20201006134829
Create Date: 2020-10-09 09:32:47.102751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20201009093245"
down_revision = "20201006134829"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "space_work_item_container_mappings",
        sa.Column("is_primary", sa.Boolean(), nullable=True),
    )
    op.create_unique_constraint(
        "uq_space_work_item_container",
        "space_work_item_container_mappings",
        ["space_id", "work_item_container_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_space_work_item_container",
        "space_work_item_container_mappings",
        type_="unique",
    )
    op.drop_column("space_work_item_container_mappings", "is_primary")
    # ### end Alembic commands ###
