"""add measured_at to progress_points

Revision ID: 20201009235422
Revises: 1b42d1ec6eb8
Create Date: 2020-10-09 23:54:23.479930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20201009235422"
down_revision = "1b42d1ec6eb8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("progress_points", sa.Column("measured_at", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("progress_points", "measured_at")
    # ### end Alembic commands ###
