"""remove objective from progress points

Revision ID: 20201110114429
Revises: 20201023135839
Create Date: 2020-11-10 11:44:31.073537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20201110114429"
down_revision = "20201023135839"
branch_labels = None
depends_on = None

CHECK_SQL = (
    "("
    "(objective_id is not null)::integer +"
    "(key_result_id is not null)::integer"
    ") = 1"
)

CHECK_CONSTRAINT_NAME = "mutually_exclusive_fk_check"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_progress_points_objective_id", table_name="progress_points")
    op.drop_constraint(
        "progress_points_objective_id_fkey", "progress_points", type_="foreignkey"
    )
    op.drop_column("progress_points", "objective_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "progress_points",
        sa.Column("objective_id", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "progress_points_objective_id_fkey",
        "progress_points",
        "objectives",
        ["objective_id"],
        ["id"],
    )
    op.create_index(
        "ix_progress_points_objective_id",
        "progress_points",
        ["objective_id"],
        unique=False,
    )
    # Add back the unique constraint check.
    op.create_check_constraint(CHECK_CONSTRAINT_NAME, "progress_points", CHECK_SQL)

    # ### end Alembic commands ###
