"""Make progress points polymorphic

Revision ID: 20200914152057
Revises: 20200826150422
Create Date: 2020-09-14 15:20:59.779829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20200914152057"
down_revision = "20200826150422"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "progress_points",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("trackable_id", sa.BigInteger(), nullable=False),
        sa.Column("trackable_type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_progress_points_trackable_id"),
        "progress_points",
        ["trackable_id", "trackable_type"],
        unique=False,
    )
    op.drop_index(
        "ix_key_result_progress_points_key_result_id",
        table_name="key_result_progress_points",
    )
    op.drop_table("key_result_progress_points")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "key_result_progress_points",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "value",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("key_result_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["key_result_id"],
            ["key_results.id"],
            name="key_result_progress_points_key_result_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="key_result_progress_points_pkey"),
    )
    op.create_index(
        "ix_key_result_progress_points_key_result_id",
        "key_result_progress_points",
        ["key_result_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_progress_points_trackable_id"), table_name="progress_points")
    op.drop_table("progress_points")
    # ### end Alembic commands ###
