"""Add external_title to work_item_containers

Revision ID: 20201215135933
Revises: 20201128160619
Create Date: 2020-12-15 13:59:36.022893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20201215135933"
down_revision = "20201128160619"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "work_item_containers", sa.Column("external_title", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("work_item_containers", "external_title")
    # ### end Alembic commands ###
