"""changes to work items

Revision ID: 20201023135839
Revises: 20201022150728
Create Date: 2020-10-23 13:58:40.221351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20201023135839"
down_revision = "20201022150728"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("work_items", sa.Column("item_type", sa.String(), nullable=True))
    op.add_column("work_items", sa.Column("planned_finish", sa.Date(), nullable=True))
    op.add_column("work_items", sa.Column("planned_start", sa.Date(), nullable=True))
    op.add_column("work_items", sa.Column("title", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("work_items", "title")
    op.drop_column("work_items", "planned_start")
    op.drop_column("work_items", "planned_finish")
    op.drop_column("work_items", "item_type")
    # ### end Alembic commands ###
