"""adding progress_percentage fields to pp

Revision ID: 20201119205629
Revises: 20201119125408
Create Date: 2020-11-19 20:56:30.906579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20201119205629"
down_revision = "20201119125408"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "progress_points",
        sa.Column("key_result_progress_percentage", sa.Integer(), nullable=False),
    )
    op.add_column(
        "progress_points",
        sa.Column("objective_progress_percentage", sa.Integer(), nullable=False),
    )
    op.execute(
        "ALTER TABLE public.progress_points "
        "ALTER COLUMN key_result_progress_percentage SET DEFAULT 0, "
        "ALTER COLUMN objective_progress_percentage SET DEFAULT 0;"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("progress_points", "objective_progress_percentage")
    op.drop_column("progress_points", "key_result_progress_percentage")
    # ### end Alembic commands ###
