"""add unique index to work_item_containers table

Revision ID: 20201011153601
Revises: 20201009235422
Create Date: 2020-10-11 15:36:03.114428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20201011153601"
down_revision = "20201009235422"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_work_item_containers_containable_type", table_name="work_item_containers"
    )
    op.create_unique_constraint(
        "uq_work_item_containers_containable_type",
        "work_item_containers",
        ["containable_type", "containable_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_work_item_containers_containable_type",
        "work_item_containers",
        type_="unique",
    )
    op.create_index(
        "ix_work_item_containers_containable_type",
        "work_item_containers",
        ["containable_type", "containable_id"],
        unique=False,
    )
    # # ### end Alembic commands ###
