"""Add comment column to pp

Revision ID: 20201221171450
Revises: 20201217145546
Create Date: 2020-12-21 17:14:52.064914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20201221171450"
down_revision = "20201217145546"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("progress_points", sa.Column("comment", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("progress_points", "comment")
    # ### end Alembic commands ###
