"""Rename polymorphic columns to external

Revision ID: 20201217145503
Revises: 20201217142412
Create Date: 2020-12-17 14:55:04.431481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20201217145503"
down_revision = "20201217142412"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "work_item_containers", sa.Column("external_id", sa.String(), nullable=False)
    )
    op.add_column(
        "work_item_containers", sa.Column("external_type", sa.String(), nullable=False)
    )
    op.create_unique_constraint(
        "ux_work_item_container_external",
        "work_item_containers",
        ["external_type", "external_id"],
    )
    op.drop_constraint(
        "uq_work_item_containers_containable_type",
        "work_item_containers",
        type_="unique",
    )
    op.drop_column("work_item_containers", "containable_id")
    op.drop_column("work_item_containers", "containable_type")
    op.add_column("work_items", sa.Column("external_id", sa.String(), nullable=False))
    op.add_column("work_items", sa.Column("external_type", sa.String(), nullable=False))
    op.create_unique_constraint(
        "ux_work_item_external", "work_items", ["external_type", "external_id"]
    )
    op.drop_constraint("uq_workable_type_workable_id", "work_items", type_="unique")
    op.drop_column("work_items", "workable_id")
    op.drop_column("work_items", "workable_type")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "work_items",
        sa.Column("workable_type", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "work_items",
        sa.Column("workable_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint(
        "uq_workable_type_workable_id", "work_items", ["workable_type", "workable_id"]
    )
    op.drop_constraint("ux_work_item_external", "work_items", type_="unique")
    op.drop_column("work_items", "external_type")
    op.drop_column("work_items", "external_id")
    op.add_column(
        "work_item_containers",
        sa.Column(
            "containable_type", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "work_item_containers",
        sa.Column("containable_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint(
        "uq_work_item_containers_containable_type",
        "work_item_containers",
        ["containable_type", "containable_id"],
    )
    op.drop_constraint(
        "ux_work_item_container_external", "work_item_containers", type_="unique"
    )
    op.drop_column("work_item_containers", "external_type")
    op.drop_column("work_item_containers", "external_id")
    # ### end Alembic commands ###
