"""Add indexed tenant_id_str field to all tables

Revision ID: 20201222120818
Revises: 20201217145546
Create Date: 2020-12-22 12:08:20.826329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20201222120818"
down_revision = "20201217145546"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "key_result_work_item_mappings",
        sa.Column("tenant_id_str", sa.String(), nullable=True),
    )
    op.create_index(
        op.f("ix_key_result_work_item_mappings_tenant_id_str"),
        "key_result_work_item_mappings",
        ["tenant_id_str"],
        unique=False,
    )
    op.add_column("key_results", sa.Column("tenant_id_str", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_key_results_tenant_id_str"),
        "key_results",
        ["tenant_id_str"],
        unique=False,
    )
    op.add_column("objectives", sa.Column("tenant_id_str", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_objectives_tenant_id_str"),
        "objectives",
        ["tenant_id_str"],
        unique=False,
    )
    op.add_column(
        "progress_points", sa.Column("tenant_id_str", sa.String(), nullable=True)
    )
    op.create_index(
        op.f("ix_progress_points_tenant_id_str"),
        "progress_points",
        ["tenant_id_str"],
        unique=False,
    )
    op.add_column(
        "space_work_item_container_mappings",
        sa.Column("tenant_id_str", sa.String(), nullable=True),
    )
    op.create_index(
        op.f("ix_space_work_item_container_mappings_tenant_id_str"),
        "space_work_item_container_mappings",
        ["tenant_id_str"],
        unique=False,
    )
    op.add_column("spaces", sa.Column("tenant_id_str", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_spaces_tenant_id_str"), "spaces", ["tenant_id_str"], unique=False
    )
    op.add_column(
        "work_item_containers", sa.Column("tenant_id_str", sa.String(), nullable=True)
    )
    op.create_index(
        op.f("ix_work_item_containers_tenant_id_str"),
        "work_item_containers",
        ["tenant_id_str"],
        unique=False,
    )
    op.add_column("work_items", sa.Column("tenant_id_str", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_work_items_tenant_id_str"),
        "work_items",
        ["tenant_id_str"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_work_items_tenant_id_str"), table_name="work_items")
    op.drop_column("work_items", "tenant_id_str", cascade=True)
    op.drop_index(
        op.f("ix_work_item_containers_tenant_id_str"), table_name="work_item_containers"
    )
    op.drop_column("work_item_containers", "tenant_id_str", cascade=True)
    op.drop_index(op.f("ix_spaces_tenant_id_str"), table_name="spaces")
    op.drop_column("spaces", "tenant_id_str", cascade=True)
    op.drop_index(
        op.f("ix_space_work_item_container_mappings_tenant_id_str"),
        table_name="space_work_item_container_mappings",
    )
    op.drop_column("space_work_item_container_mappings", "tenant_id_str", cascade=True)
    op.drop_index(
        op.f("ix_progress_points_tenant_id_str"), table_name="progress_points"
    )
    op.drop_column("progress_points", "tenant_id_str", cascade=True)
    op.drop_index(op.f("ix_objectives_tenant_id_str"), table_name="objectives")
    op.drop_column("objectives", "tenant_id_str", cascade=True)
    op.drop_index(op.f("ix_key_results_tenant_id_str"), table_name="key_results")
    op.drop_column("key_results", "tenant_id_str", cascade=True)
    op.drop_index(
        op.f("ix_key_result_work_item_mappings_tenant_id_str"),
        table_name="key_result_work_item_mappings",
    )
    op.drop_column("key_result_work_item_mappings", "tenant_id_str", cascade=True)
    # ### end Alembic commands ###
