"""change indexes to unique

Revision ID: 20201128160619
Revises: 20201120143805
Create Date: 2020-11-28 16:06:21.126300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20201128160619"
down_revision = "20201120143805"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_key_result_id_work_item_id",
        "key_result_work_item_mappings",
        ["key_result_id", "work_item_id"],
    )
    op.drop_index("ix_work_items_workable_type", table_name="work_items")
    op.create_unique_constraint(
        "uq_workable_type_workable_id", "work_items", ["workable_type", "workable_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_workable_type_workable_id", "work_items", type_="unique")
    op.create_index(
        "ix_work_items_workable_type",
        "work_items",
        ["workable_type", "workable_id"],
        unique=False,
    )
    op.drop_constraint(
        "uq_key_result_id_work_item_id", "key_result_work_item_mappings", type_="unique"
    )
    # ### end Alembic commands ###
