"""autogen fkeys from oa

Revision ID: 20201120143805
Revises: 20201119205915
Create Date: 2020-11-20 14:38:06.735685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20201120143805"
down_revision = "20201119205915"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "key_result_work_item_mappings_work_item_id_fkey",
        "key_result_work_item_mappings",
        type_="foreignkey",
    )
    op.drop_constraint(
        "key_result_work_item_mappings_key_result_id_fkey",
        "key_result_work_item_mappings",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "key_result_work_item_mapping_work_item_id_fkey",
        "key_result_work_item_mappings",
        "work_items",
        ["work_item_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "key_result_work_item_mapping_key_result_id_fkey",
        "key_result_work_item_mappings",
        "key_results",
        ["key_result_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "key_results_objective_id_fkey", "key_results", type_="foreignkey"
    )
    op.create_foreign_key(
        "key_results_objective_id_fkey",
        "key_results",
        "objectives",
        ["objective_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "progress_points_key_result_id_fkey", "progress_points", type_="foreignkey"
    )
    op.create_foreign_key(
        "progress_points_key_result_id_fkey",
        "progress_points",
        "key_results",
        ["key_result_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "space_work_item_container_mappings_space_id_fkey",
        "space_work_item_container_mappings",
        type_="foreignkey",
    )
    op.drop_constraint(
        "space_work_item_container_mappings_work_item_container_id_fkey",
        "space_work_item_container_mappings",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "space_work_item_container_mapping_space_id_fkey",
        "space_work_item_container_mappings",
        "spaces",
        ["space_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "space_work_item_container_mapping_work_item_container_id_fkey",
        "space_work_item_container_mappings",
        "work_item_containers",
        ["work_item_container_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "space_work_item_container_mapping_work_item_container_id_fkey",
        "space_work_item_container_mappings",
        type_="foreignkey",
    )
    op.drop_constraint(
        "space_work_item_container_mapping_space_id_fkey",
        "space_work_item_container_mappings",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "space_work_item_container_mappings_work_item_container_id_fkey",
        "space_work_item_container_mappings",
        "work_item_containers",
        ["work_item_container_id"],
        ["id"],
    )
    op.create_foreign_key(
        "space_work_item_container_mappings_space_id_fkey",
        "space_work_item_container_mappings",
        "spaces",
        ["space_id"],
        ["id"],
    )
    op.drop_constraint(
        "progress_points_key_result_id_fkey", "progress_points", type_="foreignkey"
    )
    op.create_foreign_key(
        "progress_points_key_result_id_fkey",
        "progress_points",
        "key_results",
        ["key_result_id"],
        ["id"],
    )
    op.drop_constraint(
        "key_results_objective_id_fkey", "key_results", type_="foreignkey"
    )
    op.create_foreign_key(
        "key_results_objective_id_fkey",
        "key_results",
        "objectives",
        ["objective_id"],
        ["id"],
    )
    op.drop_constraint(
        "key_result_work_item_mapping_key_result_id_fkey",
        "key_result_work_item_mappings",
        type_="foreignkey",
    )
    op.drop_constraint(
        "key_result_work_item_mapping_work_item_id_fkey",
        "key_result_work_item_mappings",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "key_result_work_item_mappings_key_result_id_fkey",
        "key_result_work_item_mappings",
        "key_results",
        ["key_result_id"],
        ["id"],
    )
    op.create_foreign_key(
        "key_result_work_item_mappings_work_item_id_fkey",
        "key_result_work_item_mappings",
        "work_items",
        ["work_item_id"],
        ["id"],
    )
    # ### end Alembic commands ###
