"""Add work_item_id to activity_logs

Revision ID: 20210217115341
Revises: 20210215173815
Create Date: 2021-02-17 11:53:43.280250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210217115341"
down_revision = "20210215173815"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity_logs", sa.Column("work_item_id", sa.BigInteger(), nullable=True)
    )
    op.create_index(
        op.f("ix_activity_logs_work_item_id"),
        "activity_logs",
        ["work_item_id"],
        unique=False,
    )
    op.create_foreign_key(
        "activity_logs_work_item_id_fkey",
        "activity_logs",
        "work_items",
        ["work_item_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "activity_logs_work_item_id_fkey", "activity_logs", type_="foreignkey"
    )
    op.drop_index(op.f("ix_activity_logs_work_item_id"), table_name="activity_logs")
    op.drop_column("activity_logs", "work_item_id")
    # ### end Alembic commands ###
