"""add soft delete to tables

Revision ID: 20210630102223
Revises: 20210615120642
Create Date: 2021-06-30 10:22:26.202985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210630102223"
down_revision = "20210615120642"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "key_results",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "objectives", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "progress_points",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "work_item_containers",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("work_item_containers", "deleted_at")
    op.drop_column("progress_points", "deleted_at")
    op.drop_column("objectives", "deleted_at")
    op.drop_column("key_results", "deleted_at")
    # ### end Alembic commands ###
