"""work_item_container_id is not null for objective

Revision ID: 20210526114642
Revises: 20210524143947
Create Date: 2021-05-26 11:46:45.155323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210526114642"
down_revision = "20210524143947"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure that there are no objectives with a null work_item_container_id
    op.execute("DELETE FROM objectives WHERE objectives.work_item_container_id IS NULL")

    # Change to not null
    op.alter_column(
        "objectives",
        "work_item_container_id",
        existing_type=sa.BIGINT(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "objectives", "work_item_container_id", existing_type=sa.BIGINT(), nullable=True
    )
    # ### end Alembic commands ###
