"""foreign key delete set null for parent objective id

Revision ID: 20210512161113
Revises: 20210511140516
Create Date: 2021-05-12 16:11:15.902253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210512161113"
down_revision = "20210511140516"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("objectives_parent_id_fkey", "objectives", type_="foreignkey")
    op.create_foreign_key(
        "objectives_parent_id_fkey",
        "objectives",
        "objectives",
        ["parent_objective_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("objectives_parent_id_fkey", "objectives", type_="foreignkey")
    op.create_foreign_key(
        "objectives_parent_id_fkey",
        "objectives",
        "objectives",
        ["parent_objective_id"],
        ["id"],
    )
    # ### end Alembic commands ###
