"""integration hub global tenant id in settings

Revision ID: 20210330151624
Revises: 20210330072937
Create Date: 2021-03-30 15:16:25.736412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210330151624"
down_revision = "20210330072937"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "settings", sa.Column("ih_global_tenant_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "ih_global_tenant_id")
    # ### end Alembic commands ###
