"""remove default editing levels for wics

Revision ID: 20210629092319
Revises: 20210615120642
Create Date: 2021-06-29 09:23:21.511001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210629092319"
down_revision = "20210615120642"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE work_item_containers ALTER COLUMN objective_editing_levels DROP DEFAULT;"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE work_item_containers ALTER COLUMN objective_editing_levels SET DEFAULT '[0,1,2,3]';"
    )
    # ### end Alembic commands ###
