"""Add activity_logs

Revision ID: 20210215173801
Revises: 20210213120834
Create Date: 2021-02-15 17:38:02.986429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210215173801"
down_revision = "20210213120834"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_logs",
        sa.Column("objective_id", sa.BigInteger(), nullable=False),
        sa.Column("key_result_id", sa.BigInteger(), nullable=True),
        sa.Column("progress_point_id", sa.BigInteger(), nullable=True),
        sa.Column("action", sa.String(), nullable=True),
        sa.Column("info", sa.JSON(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tenant_id_str", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["key_result_id"],
            ["key_results.id"],
            name="activity_logs_key_result_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["objective_id"],
            ["objectives.id"],
            name="activity_logs_objective_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["progress_point_id"],
            ["progress_points.id"],
            name="activity_logs_progress_point_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activity_logs_key_result_id"),
        "activity_logs",
        ["key_result_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_logs_objective_id"),
        "activity_logs",
        ["objective_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_logs_progress_point_id"),
        "activity_logs",
        ["progress_point_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_logs_tenant_id_str"),
        "activity_logs",
        ["tenant_id_str"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activity_logs_tenant_id_str"), table_name="activity_logs")
    op.drop_index(
        op.f("ix_activity_logs_progress_point_id"), table_name="activity_logs"
    )
    op.drop_index(op.f("ix_activity_logs_objective_id"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_key_result_id"), table_name="activity_logs")
    op.drop_table("activity_logs")
    # ### end Alembic commands ###
