"""adjust ux constraint for wic deletion

Revision ID: 20210713145550
Revises: 20210630144006
Create Date: 2021-07-13 14:55:52.616398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20210713145550"
down_revision = "20210630144006"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "key_results",
        sa.Column(
            "deleted_at_epoch",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.drop_column("key_results", "deleted_at")
    op.add_column(
        "objectives",
        sa.Column(
            "deleted_at_epoch",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.drop_column("objectives", "deleted_at")
    op.add_column(
        "progress_points",
        sa.Column(
            "deleted_at_epoch",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.drop_column("progress_points", "deleted_at")
    op.add_column(
        "work_item_containers",
        sa.Column(
            "deleted_at_epoch",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.drop_constraint(
        "ux_work_item_container_external", "work_item_containers", type_="unique"
    )
    op.create_unique_constraint(
        "ux_work_item_container_external",
        "work_item_containers",
        ["external_type", "external_id", "deleted_at_epoch"],
    )
    op.drop_column("work_item_containers", "deleted_at")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "work_item_containers",
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(
        "ux_work_item_container_external", "work_item_containers", type_="unique"
    )
    op.create_unique_constraint(
        "ux_work_item_container_external",
        "work_item_containers",
        ["external_type", "external_id"],
    )
    op.drop_column("work_item_containers", "deleted_at_epoch")
    op.add_column(
        "progress_points",
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("progress_points", "deleted_at_epoch")
    op.add_column(
        "objectives",
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("objectives", "deleted_at_epoch")
    op.add_column(
        "key_results",
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("key_results", "deleted_at_epoch")
    # ### end Alembic commands ###
