"""objective editing levels for wics

Revision ID: 20210415142902
Revises: 20210413114056
Create Date: 2021-04-15 14:29:04.506197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20210415142902"
down_revision = "20210413114056"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "work_item_containers",
        sa.Column("objective_editing_levels", sa.JSON(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("work_item_containers", "objective_editing_levels")
    # ### end Alembic commands ###
