"""Add app_created_by to all tables

Revision ID: 20210310061608
Revises: 20210220233948
Create Date: 2021-03-10 06:16:13.872623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210310061608"
down_revision = "20210220233948"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity_logs", sa.Column("app_created_by", sa.BigInteger(), nullable=True)
    )
    op.create_index(
        op.f("ix_activity_logs_app_created_by"),
        "activity_logs",
        ["app_created_by"],
        unique=False,
    )
    op.add_column(
        "key_result_work_item_mappings",
        sa.Column("app_created_by", sa.BigInteger(), nullable=True),
    )
    op.create_index(
        op.f("ix_key_result_work_item_mappings_app_created_by"),
        "key_result_work_item_mappings",
        ["app_created_by"],
        unique=False,
    )
    op.add_column(
        "key_results", sa.Column("app_created_by", sa.BigInteger(), nullable=True)
    )
    op.create_index(
        op.f("ix_key_results_app_created_by"),
        "key_results",
        ["app_created_by"],
        unique=False,
    )
    op.add_column(
        "objectives", sa.Column("app_created_by", sa.BigInteger(), nullable=True)
    )
    op.create_index(
        op.f("ix_objectives_app_created_by"),
        "objectives",
        ["app_created_by"],
        unique=False,
    )
    op.add_column(
        "progress_points", sa.Column("app_created_by", sa.BigInteger(), nullable=True)
    )
    op.create_index(
        op.f("ix_progress_points_app_created_by"),
        "progress_points",
        ["app_created_by"],
        unique=False,
    )
    op.add_column(
        "settings", sa.Column("app_created_by", sa.BigInteger(), nullable=True)
    )
    op.create_index(
        op.f("ix_settings_app_created_by"), "settings", ["app_created_by"], unique=False
    )
    op.add_column(
        "space_work_item_container_mappings",
        sa.Column("app_created_by", sa.BigInteger(), nullable=True),
    )
    op.create_index(
        op.f("ix_space_work_item_container_mappings_app_created_by"),
        "space_work_item_container_mappings",
        ["app_created_by"],
        unique=False,
    )
    op.add_column("spaces", sa.Column("app_created_by", sa.BigInteger(), nullable=True))
    op.create_index(
        op.f("ix_spaces_app_created_by"), "spaces", ["app_created_by"], unique=False
    )
    op.add_column(
        "work_item_containers",
        sa.Column("app_created_by", sa.BigInteger(), nullable=True),
    )
    op.create_index(
        op.f("ix_work_item_containers_app_created_by"),
        "work_item_containers",
        ["app_created_by"],
        unique=False,
    )
    op.add_column(
        "work_items", sa.Column("app_created_by", sa.BigInteger(), nullable=True)
    )
    op.create_index(
        op.f("ix_work_items_app_created_by"),
        "work_items",
        ["app_created_by"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_work_items_app_created_by"), table_name="work_items")
    op.drop_column("work_items", "app_created_by")
    op.drop_index(
        op.f("ix_work_item_containers_app_created_by"),
        table_name="work_item_containers",
    )
    op.drop_column("work_item_containers", "app_created_by")
    op.drop_index(op.f("ix_spaces_app_created_by"), table_name="spaces")
    op.drop_column("spaces", "app_created_by")
    op.drop_index(
        op.f("ix_space_work_item_container_mappings_app_created_by"),
        table_name="space_work_item_container_mappings",
    )
    op.drop_column("space_work_item_container_mappings", "app_created_by")
    op.drop_index(op.f("ix_settings_app_created_by"), table_name="settings")
    op.drop_column("settings", "app_created_by")
    op.drop_index(
        op.f("ix_progress_points_app_created_by"), table_name="progress_points"
    )
    op.drop_column("progress_points", "app_created_by")
    op.drop_index(op.f("ix_objectives_app_created_by"), table_name="objectives")
    op.drop_column("objectives", "app_created_by")
    op.drop_index(op.f("ix_key_results_app_created_by"), table_name="key_results")
    op.drop_column("key_results", "app_created_by")
    op.drop_index(
        op.f("ix_key_result_work_item_mappings_app_created_by"),
        table_name="key_result_work_item_mappings",
    )
    op.drop_column("key_result_work_item_mappings", "app_created_by")
    op.drop_index(op.f("ix_activity_logs_app_created_by"), table_name="activity_logs")
    op.drop_column("activity_logs", "app_created_by")
    # ### end Alembic commands ###
