"""create tenant migration log

Revision ID: 20211026133314
Revises: 20210831110925
Create Date: 2021-10-26 13:33:16.889766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20211026133314"
down_revision = "20210831110925"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenant_migration_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("original_tenant_id_str", sa.String(), nullable=True),
        sa.Column("new_tenant_id_str", sa.String(), nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tenant_migration_logs")
    # ### end Alembic commands ###
