"""integration hub subscription logging columns

Revision ID: 20210119172936
Revises: 20210119115141
Create Date: 2021-01-19 17:29:37.488122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210119172936"
down_revision = "20210119115141"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "work_items", sa.Column("ih_subscription_response", sa.JSON(), nullable=True)
    )
    op.add_column(
        "work_items", sa.Column("latest_ih_message", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("work_items", "latest_ih_message")
    op.drop_column("work_items", "ih_subscription_response")
    # ### end Alembic commands ###
