"""required okr foreign key fields

Revision ID: 20210504114706
Revises: 20210504112455
Create Date: 2021-05-04 11:47:08.536916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210504114706"
down_revision = "20210504112455"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "objectives",
        "work_item_container_id",
        existing_type=sa.BIGINT(),
        nullable=False,
    )
    op.alter_column(
        "progress_points", "key_result_id", existing_type=sa.BIGINT(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "progress_points", "key_result_id", existing_type=sa.BIGINT(), nullable=True
    )
    op.alter_column(
        "objectives", "work_item_container_id", existing_type=sa.BIGINT(), nullable=True
    )
    # ### end Alembic commands ###
