"""Default for objective editing levels

Revision ID: 20210507143715
Revises: 20210504121233
Create Date: 2021-05-07 14:37:18.080857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210507143715"
down_revision = "20210504121233"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "work_item_containers",
        "objective_editing_levels",
        nullable=True,
        server_default="[0,1,2,3]",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "work_item_containers",
        "objective_editing_levels",
        nullable=True,
        server_default="[]",
    )
    # ### end Alembic commands ###
