"""work item container delete cascade to events

Revision ID: 20210504121233
Revises: 20210504114706
Create Date: 2021-05-04 12:12:36.954153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210504121233"
down_revision = "20210504114706"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_objectives_work_item_container_id", "objectives", type_="foreignkey"
    )
    op.create_foreign_key(
        "objectives_work_item_container_id_fkey",
        "objectives",
        "work_item_containers",
        ["work_item_container_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "objectives_work_item_container_id_fkey", "objectives", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_objectives_work_item_container_id",
        "objectives",
        "work_item_containers",
        ["work_item_container_id"],
        ["id"],
    )
    # ### end Alembic commands ###
