"""work_item_container_roles

Revision ID: 20210516104250
Revises: 20210512161113
Create Date: 2021-05-16 10:42:52.326635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210516104250"
down_revision = "20210512161113"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_item_container_roles",
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("work_item_container_id", sa.BigInteger(), nullable=True),
        sa.Column("okr_role", sa.String(), nullable=False),
        sa.Column("app_role", sa.String(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tenant_id_str", sa.String(), nullable=True),
        sa.Column("app_created_by", sa.BigInteger(), nullable=False),
        sa.Column("app_last_updated_by", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["work_item_container_id"],
            ["work_item_containers.id"],
            name="work_item_container_roles_work_item_container_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("app_created_by", "work_item_container_id"),
    )
    op.create_index(
        op.f("ix_work_item_container_roles_app_created_by"),
        "work_item_container_roles",
        ["app_created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_container_roles_app_last_updated_by"),
        "work_item_container_roles",
        ["app_last_updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_container_roles_tenant_id_str"),
        "work_item_container_roles",
        ["tenant_id_str"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_container_roles_work_item_container_id"),
        "work_item_container_roles",
        ["work_item_container_id"],
        unique=False,
    )
    op.alter_column(
        "objectives", "work_item_container_id", existing_type=sa.BIGINT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "objectives",
        "work_item_container_id",
        existing_type=sa.BIGINT(),
        nullable=False,
    )
    op.drop_index(
        op.f("ix_work_item_container_roles_work_item_container_id"),
        table_name="work_item_container_roles",
    )
    op.drop_index(
        op.f("ix_work_item_container_roles_tenant_id_str"),
        table_name="work_item_container_roles",
    )
    op.drop_index(
        op.f("ix_work_item_container_roles_app_last_updated_by"),
        table_name="work_item_container_roles",
    )
    op.drop_index(
        op.f("ix_work_item_container_roles_app_created_by"),
        table_name="work_item_container_roles",
    )
    op.drop_table("work_item_container_roles")
    # ### end Alembic commands ###
