"""level default is required

Revision ID: 20210317115339
Revises: 20210317114614
Create Date: 2021-03-17 11:53:41.749161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210317115339"
down_revision = "20210317114614"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "objectives", "level_depth", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "objectives", "level_depth", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
