"""make wic required and cascade on delete

Revision ID: 20210520153717
Revises: 20210520153255
Create Date: 2021-05-20 15:37:20.863524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210520153717"
down_revision = "20210520153255"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "work_item_container_roles",
        "work_item_container_id",
        existing_type=sa.BIGINT(),
        nullable=False,
    )
    op.alter_column(
        "work_items",
        "work_item_container_id",
        existing_type=sa.BIGINT(),
        nullable=False,
    )
    op.drop_constraint(
        "work_items_work_item_container_id_fkey", "work_items", type_="foreignkey"
    )
    op.create_foreign_key(
        "work_items_work_item_container_id_fkey",
        "work_items",
        "work_item_containers",
        ["work_item_container_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "work_items_work_item_container_id_fkey", "work_items", type_="foreignkey"
    )
    op.create_foreign_key(
        "work_items_work_item_container_id_fkey",
        "work_items",
        "work_item_containers",
        ["work_item_container_id"],
        ["id"],
    )
    op.alter_column(
        "work_items", "work_item_container_id", existing_type=sa.BIGINT(), nullable=True
    )
    op.alter_column(
        "work_item_container_roles",
        "work_item_container_id",
        existing_type=sa.BIGINT(),
        nullable=True,
    )
    # ### end Alembic commands ###
