"""add unique constraint to tenant_id_str on settings

Revision ID: 20210215141941
Revises: 20210213120834
Create Date: 2021-02-15 14:19:48.195994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210215141941"
down_revision = "20210213120834"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_settings_tenant_id_str", table_name="settings")
    op.create_index(
        op.f("ix_settings_tenant_id_str"), "settings", ["tenant_id_str"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_settings_tenant_id_str"), table_name="settings")
    op.create_index(
        "ix_settings_tenant_id_str", "settings", ["tenant_id_str"], unique=False
    )
    # ### end Alembic commands ###
