"""add_ih_setup_at_timestamp

Revision ID: 20210312170021
Revises: 20210220233948
Create Date: 2021-03-12 17:00:24.375074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210312170021"
down_revision = "20210220233948"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust ###
    op.add_column(
        "settings", sa.Column("ih_setup_verified_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "ih_setup_verified_at")
    # ### end Alembic commands ###
