"""add indexing to wics

Revision ID: 20210806114411
Revises: 20210805163137
Create Date: 2021-08-06 11:44:15.333443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210806114411"
down_revision = "20210805163137"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "x_work_item_container_external_id_type",
        "work_item_containers",
        ["external_type", "external_id"],
        unique=False,
    )
    op.create_index(
        "x_work_item_container_external_id_type_tenant",
        "work_item_containers",
        ["external_type", "external_id", "tenant_id_str"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "x_work_item_container_external_id_type_tenant",
        table_name="work_item_containers",
    )
    op.drop_index(
        "x_work_item_container_external_id_type", table_name="work_item_containers"
    )
    # ### end Alembic commands ###
