"""Add levels, level_depth, and parent_id support

Revision ID: 20210202105056
Revises: 20210119172936
Create Date: 2021-02-02 10:50:58.833178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210202105056"
down_revision = "20210119172936"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "level_configs",
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tenant_id_str", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_level_configs_tenant_id_str"),
        "level_configs",
        ["tenant_id_str"],
        unique=False,
    )
    op.add_column("objectives", sa.Column("level_depth", sa.Integer(), nullable=True))
    op.add_column(
        "objectives", sa.Column("parent_objective_id", sa.BigInteger(), nullable=True)
    )
    op.create_index(
        op.f("ix_objectives_parent_objective_id"),
        "objectives",
        ["parent_objective_id"],
        unique=False,
    )
    op.create_foreign_key(
        "objectives_parent_id_fkey",
        "objectives",
        "objectives",
        ["parent_objective_id"],
        ["id"],
    )
    op.add_column(
        "work_item_containers",
        sa.Column("level_depth_default", sa.Integer(), nullable=True),
    )
    op.execute(
        "ALTER TABLE level_configs ALTER COLUMN data SET DEFAULT "
        '\'[{ "depth": 0, "name": "Company" },'
        '{ "depth": 1, "name": "Value Stream" },'
        '{ "depth": 2, "name": "Department" },'
        '{ "depth": 3, "name": "Program" },'
        '{ "depth": 4, "name": "Team", "default": true }]\';'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("work_item_containers", "level_depth_default")
    op.drop_constraint("objectives_parent_id_fkey", "objectives", type_="foreignkey")
    op.drop_index(op.f("ix_objectives_parent_objective_id"), table_name="objectives")
    op.drop_column("objectives", "parent_objective_id")
    op.drop_column("objectives", "level_depth")
    op.drop_index(op.f("ix_level_configs_tenant_id_str"), table_name="level_configs")
    op.drop_table("level_configs")
    # ### end Alembic commands ###
