"""activity log removing foreign key constraints

Revision ID: 20210322131038
Revises: 20210317115339
Create Date: 2021-03-22 13:10:42.849912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210322131038"
down_revision = "20210317115339"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "activity_logs_work_item_id_fkey", "activity_logs", type_="foreignkey"
    )
    op.drop_constraint(
        "activity_logs_progress_point_id_fkey", "activity_logs", type_="foreignkey"
    )
    op.drop_constraint(
        "activity_logs_key_result_id_fkey", "activity_logs", type_="foreignkey"
    )
    op.drop_constraint(
        "activity_logs_objective_id_fkey", "activity_logs", type_="foreignkey"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "activity_logs_objective_id_fkey",
        "activity_logs",
        "objectives",
        ["objective_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "activity_logs_key_result_id_fkey",
        "activity_logs",
        "key_results",
        ["key_result_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "activity_logs_progress_point_id_fkey",
        "activity_logs",
        "progress_points",
        ["progress_point_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "activity_logs_work_item_id_fkey",
        "activity_logs",
        "work_items",
        ["work_item_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
