"""Remove level_configs and add settings

Revision ID: 20210213120448
Revises: 20210205100957
Create Date: 2021-02-13 12:04:53.290068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20210213120448"
down_revision = "20210205100957"
branch_labels = None
depends_on = None

KR_VIEW_NAME = "key_result_work_items_view"
KR_VIEW_SQL = (
    f"CREATE OR REPLACE VIEW {KR_VIEW_NAME} AS "
    "SELECT mappings.key_result_id, "
    "work_items.id, "
    "work_items.state, "
    "work_items.work_item_container_id, "
    "work_items.created_at, "
    "work_items.updated_at, "
    "work_items.item_type, "
    "work_items.planned_finish, "
    "work_items.planned_start, "
    "work_items.title, "
    "work_items.external_id, "
    "work_items.external_type, "
    "work_items.tenant_id_str "
    "FROM key_result_work_item_mappings mappings "
    "LEFT JOIN work_items ON mappings.work_item_id = work_items.id"
)

SPACE_VIEW_NAME = "space_work_item_containers_view"
SPACE_VIEW_SQL = (
    f"CREATE OR REPLACE VIEW {SPACE_VIEW_NAME} AS "
    "SELECT mappings.space_id, "
    "wics.id, "
    "wics.created_at, "
    "wics.updated_at, "
    "wics.external_title, "
    "wics.external_id, "
    "wics.external_type, "
    "wics.tenant_id_str "
    "FROM space_work_item_container_mappings mappings "
    "LEFT JOIN work_item_containers wics ON mappings.work_item_container_id = wics.id"
)


def upgrade():
    op.execute(KR_VIEW_SQL)
    op.execute(SPACE_VIEW_SQL)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("level_config", sa.JSON(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tenant_id_str", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_settings_tenant_id_str"), "settings", ["tenant_id_str"], unique=False
    )
    op.drop_index("ix_level_configs_tenant_id_str", table_name="level_configs")
    op.drop_table("level_configs")
    op.drop_column("work_item_containers", "deprecated_external_type")
    op.drop_column("work_items", "deprecated_external_type")

    op.execute(
        "ALTER TABLE settings ALTER COLUMN level_config SET DEFAULT "
        '\'[{ "depth": 0, "name": "Enterprise", "color": "#ba8aa4", "is_default": false },'
        '{ "depth": 1, "name": "Value Stream", "color": "#f87b55", "is_default": false },'
        '{ "depth": 2, "name": "Program", "color": "#8ab98e", "is_default": false },'
        '{ "depth": 3, "name": "Team", "color": "#608eb6", "is_default": true }]\';'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "work_items",
        sa.Column(
            "deprecated_external_type", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "work_item_containers",
        sa.Column(
            "deprecated_external_type", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.create_table(
        "level_configs",
        sa.Column(
            "data",
            postgresql.JSON(astext_type=sa.Text()),
            server_default=sa.text(
                '\'[{ "depth": 0, "name": "Company" },{ "depth": 1, "name": "Value Stream" },{ "depth": 2, "name": "Department" },{ "depth": 3, "name": "Program" },{ "depth": 4, "name": "Team", "default": true }]\'::json'
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("tenant_id_str", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="level_configs_pkey"),
    )
    op.create_index(
        "ix_level_configs_tenant_id_str",
        "level_configs",
        ["tenant_id_str"],
        unique=False,
    )
    op.drop_index(op.f("ix_settings_tenant_id_str"), table_name="settings")
    op.drop_table("settings")
    # ### end Alembic commands ###
