"""modify composite index for roles

Revision ID: 20210809100526
Revises: 20210806114411
Create Date: 2021-08-09 10:05:28.468008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210809100526"
down_revision = "20210806114411"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "work_item_container_roles_app_created_by_work_item_containe_key",
        "work_item_container_roles",
        type_="unique",
    )
    op.create_unique_constraint(
        None,
        "work_item_container_roles",
        ["app_created_by", "work_item_container_id", "tenant_id_str"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "work_item_container_roles", type_="unique")
    op.create_unique_constraint(
        "work_item_container_roles_app_created_by_work_item_containe_key",
        "work_item_container_roles",
        ["app_created_by", "work_item_container_id"],
    )
    # ### end Alembic commands ###
