"""Add app_owned_by to objectives and key_results

Revision ID: 20210310062009
Revises: 20210310061608
Create Date: 2021-03-10 06:20:11.286711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210310062009"
down_revision = "20210310061608"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "key_results", sa.Column("app_owned_by", sa.BigInteger(), nullable=True)
    )
    op.create_index(
        op.f("ix_key_results_app_owned_by"),
        "key_results",
        ["app_owned_by"],
        unique=False,
    )
    op.add_column(
        "objectives", sa.Column("app_owned_by", sa.BigInteger(), nullable=True)
    )
    op.create_index(
        op.f("ix_objectives_app_owned_by"), "objectives", ["app_owned_by"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_objectives_app_owned_by"), table_name="objectives")
    op.drop_column("objectives", "app_owned_by")
    op.drop_index(op.f("ix_key_results_app_owned_by"), table_name="key_results")
    op.drop_column("key_results", "app_owned_by")
    # ### end Alembic commands ###
