"""Add app_name to WokItem and WorkItemContainer for backward compatibility

Revision ID: 20220606101013
Revises: 20220225201750
Create Date: 2022-06-06 10:10:16.196537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import Computed, inspect

revision = "20220606101013"
down_revision = "20220225201750"
branch_labels = None
depends_on = None


def column_exists(table_name, column_name):
    bind = op.get_context().bind
    insp = inspect(bind)
    columns = insp.get_columns(table_name)
    return any(c["name"] == column_name for c in columns)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists("work_item_containers", "app_name"):
        op.add_column(
            "work_item_containers", sa.Column("app_name", sa.String(), nullable=True)
        )

    if not column_exists("work_items", "app_name"):
        op.add_column("work_items", sa.Column("app_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("work_items", "app_name")
    op.drop_column("work_item_containers", "app_name")
    # ### end Alembic commands ###
