"""add_pvid_and_tenant_group_id_fields

Revision ID: 20220225200422
Revises: 20220201153415
Create Date: 2022-02-25 20:04:24.981818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import inspect

revision = "20220225200422"
down_revision = "20220201153415"
branch_labels = None
depends_on = None


def column_exists(table_name, column_name):
    bind = op.get_context().bind
    insp = inspect(bind)
    columns = insp.get_columns(table_name)
    return any(c["name"] == column_name for c in columns)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists("activity_logs", "tenant_group_id_str"):
        op.add_column(
            "activity_logs",
            sa.Column("tenant_group_id_str", sa.String(), nullable=True),
        )

    if not column_exists("activity_logs", "created_by"):
        op.add_column(
            "activity_logs", sa.Column("created_by", sa.String(), nullable=True)
        )
        op.create_index(
            op.f("ix_activity_logs_created_by"),
            "activity_logs",
            ["created_by"],
            unique=False,
        )
        op.create_index(
            op.f("ix_activity_logs_tenant_group_id_str"),
            "activity_logs",
            ["tenant_group_id_str"],
            unique=False,
        )

    if not column_exists("activity_logs", "last_updated_by"):
        op.add_column(
            "activity_logs", sa.Column("last_updated_by", sa.String(), nullable=True)
        )
        op.create_index(
            op.f("ix_activity_logs_last_updated_by"),
            "activity_logs",
            ["last_updated_by"],
            unique=False,
        )

    if not column_exists("key_result_work_item_mappings", "tenant_group_id_str"):
        op.add_column(
            "key_result_work_item_mappings",
            sa.Column("tenant_group_id_str", sa.String(), nullable=True),
        )
        op.create_index(
            op.f("ix_key_result_work_item_mappings_tenant_group_id_str"),
            "key_result_work_item_mappings",
            ["tenant_group_id_str"],
            unique=False,
        )

    if not column_exists("key_result_work_item_mappings", "created_by"):
        op.add_column(
            "key_result_work_item_mappings",
            sa.Column("created_by", sa.String(), nullable=True),
        )
        op.create_index(
            op.f("ix_key_result_work_item_mappings_created_by"),
            "key_result_work_item_mappings",
            ["created_by"],
            unique=False,
        )

    if not column_exists("key_result_work_item_mappings", "last_updated_by"):
        op.add_column(
            "key_result_work_item_mappings",
            sa.Column("last_updated_by", sa.String(), nullable=True),
        )
        op.create_index(
            op.f("ix_key_result_work_item_mappings_last_updated_by"),
            "key_result_work_item_mappings",
            ["last_updated_by"],
            unique=False,
        )

    if not column_exists("key_results", "owned_by"):
        op.add_column("key_results", sa.Column("owned_by", sa.String(), nullable=True))
        op.create_index(
            op.f("ix_key_results_owned_by"), "key_results", ["owned_by"], unique=False
        )

    if not column_exists("key_results", "tenant_group_id_str"):
        op.add_column(
            "key_results", sa.Column("tenant_group_id_str", sa.String(), nullable=True)
        )
        op.create_index(
            op.f("ix_key_results_tenant_group_id_str"),
            "key_results",
            ["tenant_group_id_str"],
            unique=False,
        )

    if not column_exists("key_results", "created_by"):
        op.add_column(
            "key_results", sa.Column("created_by", sa.String(), nullable=True)
        )
        op.create_index(
            op.f("ix_key_results_created_by"),
            "key_results",
            ["created_by"],
            unique=False,
        )

    if not column_exists("key_results", "last_updated_by"):
        op.add_column(
            "key_results", sa.Column("last_updated_by", sa.String(), nullable=True)
        )
        op.create_index(
            op.f("ix_key_results_last_updated_by"),
            "key_results",
            ["last_updated_by"],
            unique=False,
        )

    if not column_exists("objectives", "owned_by"):
        op.add_column("objectives", sa.Column("owned_by", sa.String(), nullable=True))
        op.create_index(
            op.f("ix_objectives_owned_by"), "objectives", ["owned_by"], unique=False
        )

    if not column_exists("objectives", "tenant_group_id_str"):
        op.add_column(
            "objectives", sa.Column("tenant_group_id_str", sa.String(), nullable=True)
        )
        op.create_index(
            op.f("ix_objectives_tenant_group_id_str"),
            "objectives",
            ["tenant_group_id_str"],
            unique=False,
        )

    if not column_exists("objectives", "created_by"):
        op.add_column("objectives", sa.Column("created_by", sa.String(), nullable=True))
        op.create_index(
            op.f("ix_objectives_created_by"), "objectives", ["created_by"], unique=False
        )

    if not column_exists("objectives", "last_updated_by"):
        op.add_column(
            "objectives", sa.Column("last_updated_by", sa.String(), nullable=True)
        )
        op.create_index(
            op.f("ix_objectives_last_updated_by"),
            "objectives",
            ["last_updated_by"],
            unique=False,
        )

    if not column_exists("progress_points", "tenant_group_id_str"):
        op.add_column(
            "progress_points",
            sa.Column("tenant_group_id_str", sa.String(), nullable=True),
        )
        op.create_index(
            op.f("ix_progress_points_tenant_group_id_str"),
            "progress_points",
            ["tenant_group_id_str"],
            unique=False,
        )

    if not column_exists("progress_points", "created_by"):
        op.add_column(
            "progress_points", sa.Column("created_by", sa.String(), nullable=True)
        )
        op.create_index(
            op.f("ix_progress_points_created_by"),
            "progress_points",
            ["created_by"],
            unique=False,
        )

    if not column_exists("progress_points", "last_updated_by"):
        op.add_column(
            "progress_points", sa.Column("last_updated_by", sa.String(), nullable=True)
        )
        op.create_index(
            op.f("ix_progress_points_last_updated_by"),
            "progress_points",
            ["last_updated_by"],
            unique=False,
        )

    if not column_exists("settings", "tenant_group_id_str"):
        op.add_column(
            "settings", sa.Column("tenant_group_id_str", sa.String(), nullable=True)
        )
        op.create_index(
            op.f("ix_settings_tenant_group_id_str"),
            "settings",
            ["tenant_group_id_str"],
            unique=False,
        )

    if not column_exists("settings", "created_by"):
        op.add_column("settings", sa.Column("created_by", sa.String(), nullable=True))
        op.create_index(
            op.f("ix_settings_created_by"), "settings", ["created_by"], unique=False
        )

    if not column_exists("settings", "last_updated_by"):
        op.add_column(
            "settings", sa.Column("last_updated_by", sa.String(), nullable=True)
        )
        op.create_index(
            op.f("ix_settings_last_updated_by"),
            "settings",
            ["last_updated_by"],
            unique=False,
        )

    if not column_exists("space_work_item_container_mappings", "tenant_group_id_str"):
        op.add_column(
            "space_work_item_container_mappings",
            sa.Column("tenant_group_id_str", sa.String(), nullable=True),
        )
        op.create_index(
            op.f("ix_space_work_item_container_mappings_tenant_group_id_str"),
            "space_work_item_container_mappings",
            ["tenant_group_id_str"],
            unique=False,
        )
    if not column_exists("space_work_item_container_mappings", "created_by"):
        op.add_column(
            "space_work_item_container_mappings",
            sa.Column("created_by", sa.String(), nullable=True),
        )
        op.create_index(
            op.f("ix_space_work_item_container_mappings_created_by"),
            "space_work_item_container_mappings",
            ["created_by"],
            unique=False,
        )
    if not column_exists("space_work_item_container_mappings", "last_updated_by"):
        op.add_column(
            "space_work_item_container_mappings",
            sa.Column("last_updated_by", sa.String(), nullable=True),
        )
        op.create_index(
            op.f("ix_space_work_item_container_mappings_last_updated_by"),
            "space_work_item_container_mappings",
            ["last_updated_by"],
            unique=False,
        )

    if not column_exists("spaces", "tenant_group_id_str"):
        op.add_column(
            "spaces", sa.Column("tenant_group_id_str", sa.String(), nullable=True)
        )
        op.create_index(
            op.f("ix_spaces_tenant_group_id_str"),
            "spaces",
            ["tenant_group_id_str"],
            unique=False,
        )
    if not column_exists("spaces", "created_by"):
        op.add_column("spaces", sa.Column("created_by", sa.String(), nullable=True))
        op.create_index(
            op.f("ix_spaces_created_by"), "spaces", ["created_by"], unique=False
        )
    if not column_exists("spaces", "last_updated_by"):
        op.add_column(
            "spaces", sa.Column("last_updated_by", sa.String(), nullable=True)
        )
        op.create_index(
            op.f("ix_spaces_last_updated_by"),
            "spaces",
            ["last_updated_by"],
            unique=False,
        )

    if not column_exists("work_item_container_roles", "tenant_group_id_str"):
        op.add_column(
            "work_item_container_roles",
            sa.Column("tenant_group_id_str", sa.String(), nullable=True),
        )
        op.create_index(
            op.f("ix_work_item_container_roles_tenant_group_id_str"),
            "work_item_container_roles",
            ["tenant_group_id_str"],
            unique=False,
        )

    if not column_exists("work_item_container_roles", "created_by"):
        op.add_column(
            "work_item_container_roles",
            sa.Column("created_by", sa.String(), nullable=True),
        )
        op.create_index(
            op.f("ix_work_item_container_roles_created_by"),
            "work_item_container_roles",
            ["created_by"],
            unique=False,
        )

    if not column_exists("work_item_container_roles", "last_updated_by"):
        op.add_column(
            "work_item_container_roles",
            sa.Column("last_updated_by", sa.String(), nullable=True),
        )
        op.create_index(
            op.f("ix_work_item_container_roles_last_updated_by"),
            "work_item_container_roles",
            ["last_updated_by"],
            unique=False,
        )

    if not column_exists("work_item_containers", "tenant_group_id_str"):
        op.add_column(
            "work_item_containers",
            sa.Column("tenant_group_id_str", sa.String(), nullable=True),
        )
        op.create_index(
            op.f("ix_work_item_containers_tenant_group_id_str"),
            "work_item_containers",
            ["tenant_group_id_str"],
            unique=False,
        )
    if not column_exists("work_item_containers", "created_by"):
        op.add_column(
            "work_item_containers", sa.Column("created_by", sa.String(), nullable=True)
        )
        op.create_index(
            op.f("ix_work_item_containers_created_by"),
            "work_item_containers",
            ["created_by"],
            unique=False,
        )
    if not column_exists("work_item_containers", "last_updated_by"):
        op.add_column(
            "work_item_containers",
            sa.Column("last_updated_by", sa.String(), nullable=True),
        )
        op.create_index(
            op.f("ix_work_item_containers_last_updated_by"),
            "work_item_containers",
            ["last_updated_by"],
            unique=False,
        )

    if not column_exists("work_items", "tenant_group_id_str"):
        op.add_column(
            "work_items", sa.Column("tenant_group_id_str", sa.String(), nullable=True)
        )
        op.create_index(
            op.f("ix_work_items_tenant_group_id_str"),
            "work_items",
            ["tenant_group_id_str"],
            unique=False,
        )
    if not column_exists("work_items", "created_by"):
        op.add_column("work_items", sa.Column("created_by", sa.String(), nullable=True))
        op.create_index(
            op.f("ix_work_items_created_by"), "work_items", ["created_by"], unique=False
        )
    if not column_exists("work_items", "last_updated_by"):
        op.add_column(
            "work_items", sa.Column("last_updated_by", sa.String(), nullable=True)
        )
        op.create_index(
            op.f("ix_work_items_last_updated_by"),
            "work_items",
            ["last_updated_by"],
            unique=False,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_work_items_tenant_group_id_str"), table_name="work_items")
    op.drop_index(op.f("ix_work_items_last_updated_by"), table_name="work_items")
    op.drop_index(op.f("ix_work_items_created_by"), table_name="work_items")
    op.drop_column("work_items", "last_updated_by")
    op.drop_column("work_items", "created_by")
    op.drop_column("work_items", "tenant_group_id_str")
    op.drop_index(
        op.f("ix_work_item_containers_tenant_group_id_str"),
        table_name="work_item_containers",
    )
    op.drop_index(
        op.f("ix_work_item_containers_last_updated_by"),
        table_name="work_item_containers",
    )
    op.drop_index(
        op.f("ix_work_item_containers_created_by"), table_name="work_item_containers"
    )
    op.drop_column("work_item_containers", "last_updated_by")
    op.drop_column("work_item_containers", "created_by")
    op.drop_column("work_item_containers", "tenant_group_id_str")
    op.drop_index(
        op.f("ix_work_item_container_roles_tenant_group_id_str"),
        table_name="work_item_container_roles",
    )
    op.drop_index(
        op.f("ix_work_item_container_roles_last_updated_by"),
        table_name="work_item_container_roles",
    )
    op.drop_index(
        op.f("ix_work_item_container_roles_created_by"),
        table_name="work_item_container_roles",
    )
    op.drop_column("work_item_container_roles", "last_updated_by")
    op.drop_column("work_item_container_roles", "created_by")
    op.drop_column("work_item_container_roles", "tenant_group_id_str")
    op.drop_index(op.f("ix_spaces_tenant_group_id_str"), table_name="spaces")
    op.drop_index(op.f("ix_spaces_last_updated_by"), table_name="spaces")
    op.drop_index(op.f("ix_spaces_created_by"), table_name="spaces")
    op.drop_column("spaces", "last_updated_by")
    op.drop_column("spaces", "created_by")
    op.drop_column("spaces", "tenant_group_id_str")
    op.drop_index(
        op.f("ix_space_work_item_container_mappings_tenant_group_id_str"),
        table_name="space_work_item_container_mappings",
    )
    op.drop_index(
        op.f("ix_space_work_item_container_mappings_last_updated_by"),
        table_name="space_work_item_container_mappings",
    )
    op.drop_index(
        op.f("ix_space_work_item_container_mappings_created_by"),
        table_name="space_work_item_container_mappings",
    )
    op.drop_column("space_work_item_container_mappings", "last_updated_by")
    op.drop_column("space_work_item_container_mappings", "created_by")
    op.drop_column("space_work_item_container_mappings", "tenant_group_id_str")
    op.drop_index(op.f("ix_settings_tenant_group_id_str"), table_name="settings")
    op.drop_index(op.f("ix_settings_last_updated_by"), table_name="settings")
    op.drop_index(op.f("ix_settings_created_by"), table_name="settings")
    op.drop_column("settings", "last_updated_by")
    op.drop_column("settings", "created_by")
    op.drop_column("settings", "tenant_group_id_str")
    op.drop_index(
        op.f("ix_progress_points_tenant_group_id_str"), table_name="progress_points"
    )
    op.drop_index(
        op.f("ix_progress_points_last_updated_by"), table_name="progress_points"
    )
    op.drop_index(op.f("ix_progress_points_created_by"), table_name="progress_points")
    op.drop_column("progress_points", "last_updated_by")
    op.drop_column("progress_points", "created_by")
    op.drop_column("progress_points", "tenant_group_id_str")
    op.drop_index(op.f("ix_objectives_tenant_group_id_str"), table_name="objectives")
    op.drop_index(op.f("ix_objectives_owned_by"), table_name="objectives")
    op.drop_index(op.f("ix_objectives_last_updated_by"), table_name="objectives")
    op.drop_index(op.f("ix_objectives_created_by"), table_name="objectives")
    op.drop_column("objectives", "last_updated_by")
    op.drop_column("objectives", "created_by")
    op.drop_column("objectives", "tenant_group_id_str")
    op.drop_column("objectives", "owned_by")
    op.drop_index(op.f("ix_key_results_tenant_group_id_str"), table_name="key_results")
    op.drop_index(op.f("ix_key_results_owned_by"), table_name="key_results")
    op.drop_index(op.f("ix_key_results_last_updated_by"), table_name="key_results")
    op.drop_index(op.f("ix_key_results_created_by"), table_name="key_results")
    op.drop_column("key_results", "last_updated_by")
    op.drop_column("key_results", "created_by")
    op.drop_column("key_results", "tenant_group_id_str")
    op.drop_column("key_results", "owned_by")
    op.drop_index(
        op.f("ix_key_result_work_item_mappings_tenant_group_id_str"),
        table_name="key_result_work_item_mappings",
    )
    op.drop_index(
        op.f("ix_key_result_work_item_mappings_last_updated_by"),
        table_name="key_result_work_item_mappings",
    )
    op.drop_index(
        op.f("ix_key_result_work_item_mappings_created_by"),
        table_name="key_result_work_item_mappings",
    )
    op.drop_column("key_result_work_item_mappings", "last_updated_by")
    op.drop_column("key_result_work_item_mappings", "created_by")
    op.drop_column("key_result_work_item_mappings", "tenant_group_id_str")
    op.drop_index(
        op.f("ix_activity_logs_tenant_group_id_str"), table_name="activity_logs"
    )
    op.drop_index(op.f("ix_activity_logs_last_updated_by"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_created_by"), table_name="activity_logs")
    op.drop_column("activity_logs", "last_updated_by")
    op.drop_column("activity_logs", "created_by")
    op.drop_column("activity_logs", "tenant_group_id_str")
    # ### end Alembic commands ###
