"""Add PV Admin unmapped user ids log table

Revision ID: 20220818215244
Revises: 20220719185601
Create Date: 2022-08-18 21:52:47.622857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from sqlalchemy.engine.reflection import Inspector

revision = "20220818215244"
down_revision = "20220719185601"
branch_labels = None
depends_on = None


def table_exists(table_name):
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()
    return table_name in tables


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists("unmapped_user_ids_logs"):
        op.create_table(
            "unmapped_user_ids_logs",
            sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
            sa.Column("audit_id", sa.BigInteger(), nullable=True),
            sa.Column("user_id", sa.BigInteger(), nullable=True),
            sa.Column("table_name", sa.String(), nullable=True),
            sa.Column("column_name", sa.String(), nullable=True),
            sa.ForeignKeyConstraint(
                ["audit_id"],
                ["planview_id_migration_logs.id"],
                name="unmapped_user_ids_logs_planview_id_migration_logs_fkey",
                ondelete="RESTRICT",
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if table_exists("unmapped_user_ids_logs"):
        op.drop_table("unmapped_user_ids_logs")
    # ### end Alembic commands ###
