"""Add audit table for pvid migration

Revision ID: 20220719185601
Revises: 20220711162319
Create Date: 2022-07-19 18:56:05.044277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20220719185601"
down_revision = "20220711162319"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "planview_id_migration_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tenant_id_str", sa.String(), nullable=True),
        sa.Column("tenant_group_id_str", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False, server_default="in progress"),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("planview_id_migration_logs")
    # ### end Alembic commands ###
