"""alter planview unmapped user ids log table to store user ids as varchars

Revision ID: 20220819083414
Revises: 20220818215244
Create Date: 2022-08-19 08:34:18.530122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20220819083414"
down_revision = "20220818215244"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "unmapped_user_ids_logs",
        "user_id",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "unmapped_user_ids_logs",
        "user_id",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
