"""Change user id types

Revision ID: 20220704114441
Revises: 20220606121115
Create Date: 2022-07-04 11:44:43.405146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20220704114441"
down_revision = "20220606121115"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS key_result_work_items_view")
    op.execute("DROP VIEW IF EXISTS objective_progress_points_view")
    op.execute("DROP VIEW IF EXISTS work_item_key_results_view")

    op.alter_column(
        "activity_logs",
        "app_created_by",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="app_created_by::text::varchar",
    )
    op.alter_column(
        "activity_logs",
        "app_last_updated_by",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="app_last_updated_by::text::varchar",
    )

    op.alter_column(
        "key_result_work_item_mappings",
        "app_created_by",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="app_created_by::text::varchar",
    )
    op.alter_column(
        "key_result_work_item_mappings",
        "app_last_updated_by",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="app_last_updated_by::text::varchar",
    )

    op.alter_column(
        "key_results",
        "app_created_by",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="app_created_by::text::varchar",
    )
    op.alter_column(
        "key_results",
        "app_last_updated_by",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="app_last_updated_by::text::varchar",
    )
    op.alter_column(
        "key_results",
        "app_owned_by",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="app_owned_by::text::varchar",
    )

    op.alter_column(
        "objectives",
        "app_created_by",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="app_created_by::text::varchar",
    )
    op.alter_column(
        "objectives",
        "app_last_updated_by",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="app_last_updated_by::text::varchar",
    )
    op.alter_column(
        "objectives",
        "app_owned_by",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="app_owned_by::text::varchar",
    )

    op.alter_column(
        "progress_points",
        "app_created_by",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="app_created_by::text::varchar",
    )
    op.alter_column(
        "progress_points",
        "app_last_updated_by",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="app_last_updated_by::text::varchar",
    )

    op.alter_column(
        "settings",
        "app_created_by",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="app_created_by::text::varchar",
    )
    op.alter_column(
        "settings",
        "app_last_updated_by",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="app_last_updated_by::text::varchar",
    )

    op.alter_column(
        "space_work_item_container_mappings",
        "app_created_by",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="app_created_by::text::varchar",
    )
    op.alter_column(
        "space_work_item_container_mappings",
        "app_last_updated_by",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="app_last_updated_by::text::varchar",
    )

    op.alter_column(
        "spaces",
        "app_created_by",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="app_created_by::text::varchar",
    )
    op.alter_column(
        "spaces",
        "app_last_updated_by",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="app_last_updated_by::text::varchar",
    )

    op.alter_column(
        "work_item_container_roles",
        "app_created_by",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=False,
        postgresql_using="app_created_by::text::varchar",
    )
    op.alter_column(
        "work_item_container_roles",
        "app_last_updated_by",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="app_last_updated_by::text::varchar",
    )

    op.alter_column(
        "work_item_containers",
        "app_created_by",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="app_created_by::text::varchar",
    )
    op.alter_column(
        "work_item_containers",
        "app_last_updated_by",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="app_last_updated_by::text::varchar",
    )
    op.create_index(
        op.f("ix_work_item_containers_app_name"),
        "work_item_containers",
        ["app_name"],
        unique=False,
    )

    op.alter_column(
        "work_items",
        "app_created_by",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="app_created_by::text::varchar",
    )
    op.alter_column(
        "work_items",
        "app_last_updated_by",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="app_last_updated_by::text::varchar",
    )
    op.create_index(
        op.f("ix_work_items_app_name"), "work_items", ["app_name"], unique=False
    )

    op.execute(
        """
        CREATE OR REPLACE VIEW objective_progress_points_view
        AS SELECT key_results.objective_id,
        progress_points.*
        FROM key_results
        LEFT JOIN progress_points ON key_results.id = progress_points.key_result_id
        WHERE key_results.deleted_at_epoch = 0
        """
    )

    op.execute(
        "CREATE OR REPLACE VIEW key_result_work_items_view AS "
        "SELECT mappings.key_result_id, work_items.* "
        "FROM key_result_work_item_mappings AS mappings LEFT JOIN work_items "
        "ON mappings.work_item_id = work_items.id"
    )

    op.execute(
        """
        CREATE OR REPLACE VIEW work_item_key_results_view
        AS SELECT mappings.work_item_id,
        key_results.*
        FROM key_result_work_item_mappings mappings
        LEFT JOIN key_results ON mappings.key_result_id = key_results.id
        WHERE key_results.deleted_at_epoch = 0
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS key_result_work_items_view")
    op.execute("DROP VIEW IF EXISTS objective_progress_points_view")
    op.execute("DROP VIEW IF EXISTS work_item_key_results_view")

    op.drop_index(op.f("ix_work_items_app_name"), table_name="work_items")
    op.alter_column(
        "work_items",
        "app_last_updated_by",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        postgresql_using="app_last_updated_by::bigint",
    )
    op.alter_column(
        "work_items",
        "app_created_by",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        postgresql_using="app_created_by::bigint",
    )
    op.drop_index(
        op.f("ix_work_item_containers_app_name"), table_name="work_item_containers"
    )
    op.alter_column(
        "work_item_containers",
        "app_last_updated_by",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        postgresql_using="app_last_updated_by::bigint",
    )
    op.alter_column(
        "work_item_containers",
        "app_created_by",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        postgresql_using="app_created_by::bigint",
    )
    op.alter_column(
        "work_item_container_roles",
        "app_last_updated_by",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        postgresql_using="app_last_updated_by::bigint",
    )
    op.alter_column(
        "work_item_container_roles",
        "app_created_by",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        postgresql_using="app_created_by::bigint",
    )
    op.alter_column(
        "spaces",
        "app_last_updated_by",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        postgresql_using="app_last_updated_by::bigint",
    )
    op.alter_column(
        "spaces",
        "app_created_by",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        postgresql_using="app_created_by::bigint",
    )
    op.alter_column(
        "space_work_item_container_mappings",
        "app_last_updated_by",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        postgresql_using="app_last_updated_by::bigint",
    )
    op.alter_column(
        "space_work_item_container_mappings",
        "app_created_by",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        postgresql_using="app_created_by::bigint",
    )
    op.alter_column(
        "settings",
        "app_last_updated_by",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        postgresql_using="app_last_updated_by::bigint",
    )
    op.alter_column(
        "settings",
        "app_created_by",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        postgresql_using="app_created_by::bigint",
    )
    op.alter_column(
        "progress_points",
        "app_last_updated_by",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        postgresql_using="app_last_updated_by::bigint",
    )
    op.alter_column(
        "progress_points",
        "app_created_by",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        postgresql_using="app_created_by::bigint",
    )
    op.alter_column(
        "objectives",
        "app_owned_by",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        postgresql_using="app_owned_by::bigint",
    )
    op.alter_column(
        "objectives",
        "app_last_updated_by",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        postgresql_using="app_last_updated_by::bigint",
    )
    op.alter_column(
        "objectives",
        "app_created_by",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        postgresql_using="app_created_by::bigint",
    )
    op.alter_column(
        "key_results",
        "app_last_updated_by",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        postgresql_using="app_last_updated_by::bigint",
    )
    op.alter_column(
        "key_results",
        "app_created_by",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        postgresql_using="app_created_by::bigint",
    )
    op.alter_column(
        "key_results",
        "app_owned_by",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        postgresql_using="app_owned_by::bigint",
    )
    op.alter_column(
        "key_result_work_item_mappings",
        "app_last_updated_by",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        postgresql_using="app_last_updated_by::bigint",
    )
    op.alter_column(
        "key_result_work_item_mappings",
        "app_created_by",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        postgresql_using="app_created_by::bigint",
    )
    op.alter_column(
        "activity_logs",
        "app_last_updated_by",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        postgresql_using="app_last_updated_by::bigint",
    )
    op.alter_column(
        "activity_logs",
        "app_created_by",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        postgresql_using="app_created_by::bigint",
    )

    op.execute(
        """
        CREATE OR REPLACE VIEW objective_progress_points_view
        AS SELECT key_results.objective_id,
        progress_points.*
        FROM key_results
        LEFT JOIN progress_points ON key_results.id = progress_points.key_result_id
        WHERE key_results.deleted_at_epoch = 0
        """
    )

    op.execute(
        "CREATE OR REPLACE VIEW key_result_work_items_view AS "
        "SELECT mappings.key_result_id, work_items.* "
        "FROM key_result_work_item_mappings AS mappings LEFT JOIN work_items "
        "ON mappings.work_item_id = work_items.id"
    )

    op.execute(
        """
        CREATE OR REPLACE VIEW work_item_key_results_view
        AS SELECT mappings.work_item_id,
        key_results.*
        FROM key_result_work_item_mappings mappings
        LEFT JOIN key_results ON mappings.key_result_id = key_results.id
        WHERE key_results.deleted_at_epoch = 0
        """
    )
    # ### end Alembic commands ###
