"""Populate app_name field with defaults

Revision ID: 20220606121115
Revises: 20220606101013
Create Date: 2022-06-06 12:11:18.438361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20220606121115"
down_revision = "20220606101013"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        update work_item_containers
            set app_name = external_type;
    """
    )
    op.execute(
        """
        update work_items
            set app_name = external_type;
    """
    )
    # ### end Alembic commands ###


def downgrade():
    # Cannot downgrade
    pass
