"""Add indexes to some date fields

Revision ID: 20220113161444
Revises: 20211026133314
Create Date: 2022-01-13 16:14:47.648413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20220113161444"
down_revision = "20211026133314"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_key_results_achieved_at"), "key_results", ["achieved_at"], unique=False
    )
    op.create_index(
        op.f("ix_key_results_ends_at"), "key_results", ["ends_at"], unique=False
    )
    op.create_index(
        op.f("ix_key_results_starts_at"), "key_results", ["starts_at"], unique=False
    )
    op.create_index(
        op.f("ix_objectives_achieved_at"), "objectives", ["achieved_at"], unique=False
    )
    op.create_index(
        op.f("ix_objectives_ends_at"), "objectives", ["ends_at"], unique=False
    )
    op.create_index(
        op.f("ix_objectives_starts_at"), "objectives", ["starts_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_objectives_starts_at"), table_name="objectives")
    op.drop_index(op.f("ix_objectives_ends_at"), table_name="objectives")
    op.drop_index(op.f("ix_objectives_achieved_at"), table_name="objectives")
    op.drop_index(op.f("ix_key_results_starts_at"), table_name="key_results")
    op.drop_index(op.f("ix_key_results_ends_at"), table_name="key_results")
    op.drop_index(op.f("ix_key_results_achieved_at"), table_name="key_results")
    # ### end Alembic commands ###
