"""Add tenant_id_str to unique index

Revision ID: 20220201153415
Revises: 20220113165109
Create Date: 2022-02-01 15:34:20.062999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20220201153415"
down_revision = "20220113165109"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ux_work_item_container_external", "work_item_containers", type_="unique"
    )
    op.create_unique_constraint(
        "ux_work_item_container_external",
        "work_item_containers",
        ["external_type", "external_id", "deleted_at_epoch", "tenant_id_str"],
    )
    op.drop_constraint("ux_work_item_external", "work_items", type_="unique")
    op.create_unique_constraint(
        "ux_work_item_external",
        "work_items",
        ["external_type", "external_id", "tenant_id_str"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ux_work_item_external", "work_items", type_="unique")
    op.create_unique_constraint(
        "ux_work_item_external", "work_items", ["external_type", "external_id"]
    )
    op.drop_constraint(
        "ux_work_item_container_external", "work_item_containers", type_="unique"
    )
    op.create_unique_constraint(
        "ux_work_item_container_external",
        "work_item_containers",
        ["external_type", "external_id", "deleted_at_epoch"],
    )
    # ### end Alembic commands ###
