"""add_deleted_epoch_to_uq_index_progress_points

Revision ID: 20221118110041
Revises: 20220819124157
Create Date: 2022-11-18 11:00:47.418702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20221118110041"
down_revision = "20220819124157"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_key_result_id_measured_at", "progress_points", type_="unique"
    )
    op.create_unique_constraint(
        "uq_key_result_id_measured_at",
        "progress_points",
        ["key_result_id", "measured_at", "deleted_at_epoch"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_key_result_id_measured_at", "progress_points", type_="unique"
    )
    op.create_unique_constraint(
        "uq_key_result_id_measured_at",
        "progress_points",
        ["key_result_id", "measured_at"],
    )
    # ### end Alembic commands ###
