"""Add unique constraint on ca values

Revision ID: 20230911132331
Revises: 20230808103524
Create Date: 2023-09-11 13:23:36.164150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20230911132331"
down_revision = "20230808103524"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_custom_attributes_values"),
        "custom_attributes_values",
        ["object_id", "object_type", "ca_config_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_custom_attributes_values"), table_name="custom_attributes_values"
    )
    # ### end Alembic commands ###
