"""tables for custom attributes

Revision ID: 20230721171409
Revises: 20230601132218
Create Date: 2023-07-21 17:14:18.334783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20230721171409"
down_revision = "20230601132218"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "custom_attributes_configs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("ca_config_type", sa.String(), nullable=True),
        sa.Column("tooltip", sa.String(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("is_archived", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("is_mandatory", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("is_deleted", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("is_objective", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("is_keyresult", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column("tenant_id_str", sa.String(), nullable=True),
        sa.Column("tenant_group_id_str", sa.String(), nullable=True),
        sa.Column("app_created_by", sa.String(), nullable=True),
        sa.Column("app_last_updated_by", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("last_updated_by", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("LOCALTIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("LOCALTIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "deleted_at_epoch",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.execute(
        "alter table custom_attributes_configs "
        "  add column pv_tenant_id varchar generated always as "
        "    (case "
        "      when (tenant_group_id_str is not null) and "
        "           (tenant_group_id_str <> '') then tenant_group_id_str "
        "      else tenant_id_str "
        "     end) stored; "
    )

    op.execute(
        "alter table custom_attributes_configs "
        "  add column pv_created_by varchar generated always as "
        "    (case "
        "      when (created_by is not null) and "
        "           (created_by <> '') then created_by "
        "      else app_created_by "
        "     end) stored; "
    )

    op.execute(
        "alter table custom_attributes_configs "
        "  add column pv_last_updated_by varchar generated always as "
        "    (case "
        "      when (last_updated_by is not null) and "
        "           (last_updated_by <> '') then last_updated_by "
        "      else app_last_updated_by "
        "     end) stored; "
    )

    op.create_index(
        op.f("ix_custom_attributes_configs_app_created_by"),
        "custom_attributes_configs",
        ["app_created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_attributes_configs_app_last_updated_by"),
        "custom_attributes_configs",
        ["app_last_updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_attributes_configs_created_by"),
        "custom_attributes_configs",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_attributes_configs_last_updated_by"),
        "custom_attributes_configs",
        ["last_updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_attributes_configs_pv_created_by"),
        "custom_attributes_configs",
        ["pv_created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_attributes_configs_pv_last_updated_by"),
        "custom_attributes_configs",
        ["pv_last_updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_attributes_configs_pv_tenant_id"),
        "custom_attributes_configs",
        ["pv_tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_attributes_configs_tenant_group_id_str"),
        "custom_attributes_configs",
        ["tenant_group_id_str"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_attributes_configs_tenant_id_str"),
        "custom_attributes_configs",
        ["tenant_id_str"],
        unique=False,
    )
    op.create_table(
        "custom_attributes_values",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=True),
        sa.Column("ca_config_id", sa.Integer(), nullable=True),
        sa.Column("object_type", sa.String(), nullable=True),
        sa.Column("tooltip", sa.String(), nullable=True),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column("tenant_id_str", sa.String(), nullable=True),
        sa.Column("tenant_group_id_str", sa.String(), nullable=True),
        sa.Column("app_created_by", sa.String(), nullable=True),
        sa.Column("app_last_updated_by", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("last_updated_by", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("LOCALTIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("LOCALTIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "deleted_at_epoch",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ca_config_id"],
            ["custom_attributes_configs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.execute(
        "alter table custom_attributes_values "
        "  add column pv_tenant_id varchar generated always as "
        "    (case "
        "      when (tenant_group_id_str is not null) and "
        "           (tenant_group_id_str <> '') then tenant_group_id_str "
        "      else tenant_id_str "
        "     end) stored; "
    )

    op.execute(
        "alter table custom_attributes_values "
        "  add column pv_created_by varchar generated always as "
        "    (case "
        "      when (created_by is not null) and "
        "           (created_by <> '') then created_by "
        "      else app_created_by "
        "     end) stored; "
    )

    op.execute(
        "alter table custom_attributes_values "
        "  add column pv_last_updated_by varchar generated always as "
        "    (case "
        "      when (last_updated_by is not null) and "
        "           (last_updated_by <> '') then last_updated_by "
        "      else app_last_updated_by "
        "     end) stored; "
    )

    op.create_index(
        op.f("ix_custom_attributes_values_app_created_by"),
        "custom_attributes_values",
        ["app_created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_attributes_values_app_last_updated_by"),
        "custom_attributes_values",
        ["app_last_updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_attributes_values_created_by"),
        "custom_attributes_values",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_attributes_values_last_updated_by"),
        "custom_attributes_values",
        ["last_updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_attributes_values_pv_created_by"),
        "custom_attributes_values",
        ["pv_created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_attributes_values_pv_last_updated_by"),
        "custom_attributes_values",
        ["pv_last_updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_attributes_values_pv_tenant_id"),
        "custom_attributes_values",
        ["pv_tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_attributes_values_tenant_group_id_str"),
        "custom_attributes_values",
        ["tenant_group_id_str"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_attributes_values_tenant_id_str"),
        "custom_attributes_values",
        ["tenant_id_str"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_custom_attributes_values_tenant_id_str"),
        table_name="custom_attributes_values",
    )
    op.drop_index(
        op.f("ix_custom_attributes_values_tenant_group_id_str"),
        table_name="custom_attributes_values",
    )
    op.drop_index(
        op.f("ix_custom_attributes_values_pv_tenant_id"),
        table_name="custom_attributes_values",
    )
    op.drop_index(
        op.f("ix_custom_attributes_values_pv_last_updated_by"),
        table_name="custom_attributes_values",
    )
    op.drop_index(
        op.f("ix_custom_attributes_values_pv_created_by"),
        table_name="custom_attributes_values",
    )
    op.drop_index(
        op.f("ix_custom_attributes_values_last_updated_by"),
        table_name="custom_attributes_values",
    )
    op.drop_index(
        op.f("ix_custom_attributes_values_created_by"),
        table_name="custom_attributes_values",
    )
    op.drop_index(
        op.f("ix_custom_attributes_values_app_last_updated_by"),
        table_name="custom_attributes_values",
    )
    op.drop_index(
        op.f("ix_custom_attributes_values_app_created_by"),
        table_name="custom_attributes_values",
    )
    op.drop_table("custom_attributes_values")
    op.drop_index(
        op.f("ix_custom_attributes_configs_tenant_id_str"),
        table_name="custom_attributes_configs",
    )
    op.drop_index(
        op.f("ix_custom_attributes_configs_tenant_group_id_str"),
        table_name="custom_attributes_configs",
    )
    op.drop_index(
        op.f("ix_custom_attributes_configs_pv_tenant_id"),
        table_name="custom_attributes_configs",
    )
    op.drop_index(
        op.f("ix_custom_attributes_configs_pv_last_updated_by"),
        table_name="custom_attributes_configs",
    )
    op.drop_index(
        op.f("ix_custom_attributes_configs_pv_created_by"),
        table_name="custom_attributes_configs",
    )
    op.drop_index(
        op.f("ix_custom_attributes_configs_last_updated_by"),
        table_name="custom_attributes_configs",
    )
    op.drop_index(
        op.f("ix_custom_attributes_configs_created_by"),
        table_name="custom_attributes_configs",
    )
    op.drop_index(
        op.f("ix_custom_attributes_configs_app_last_updated_by"),
        table_name="custom_attributes_configs",
    )
    op.drop_index(
        op.f("ix_custom_attributes_configs_app_created_by"),
        table_name="custom_attributes_configs",
    )
    op.drop_table("custom_attributes_configs")
    # ### end Alembic commands ###
