"""Add additional columns and tables

Revision ID: 20230808103524
Revises: 20230721171409
Create Date: 2023-08-08 10:35:31.033531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20230808103524"
down_revision = "20230721171409"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "custom_attributes_settings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("tenant_id_str", sa.String(), nullable=True),
        sa.Column("tenant_group_id_str", sa.String(), nullable=True),
        sa.Column("app_created_by", sa.String(), nullable=True),
        sa.Column("app_last_updated_by", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("last_updated_by", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("LOCALTIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("LOCALTIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "deleted_at_epoch",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.execute(
        "alter table custom_attributes_settings "
        "  add column pv_tenant_id varchar generated always as "
        "    (case "
        "      when (tenant_group_id_str is not null) and "
        "           (tenant_group_id_str <> '') then tenant_group_id_str "
        "      else tenant_id_str "
        "     end) stored; "
    )

    op.execute(
        "alter table custom_attributes_settings "
        "  add column pv_created_by varchar generated always as "
        "    (case "
        "      when (created_by is not null) and "
        "           (created_by <> '') then created_by "
        "      else app_created_by "
        "     end) stored; "
    )

    op.execute(
        "alter table custom_attributes_settings "
        "  add column pv_last_updated_by varchar generated always as "
        "    (case "
        "      when (last_updated_by is not null) and "
        "           (last_updated_by <> '') then last_updated_by "
        "      else app_last_updated_by "
        "     end) stored; "
    )
    op.create_index(
        op.f("ix_custom_attributes_settings_app_created_by"),
        "custom_attributes_settings",
        ["app_created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_attributes_settings_app_last_updated_by"),
        "custom_attributes_settings",
        ["app_last_updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_attributes_settings_created_by"),
        "custom_attributes_settings",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_attributes_settings_last_updated_by"),
        "custom_attributes_settings",
        ["last_updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_attributes_settings_pv_created_by"),
        "custom_attributes_settings",
        ["pv_created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_attributes_settings_pv_last_updated_by"),
        "custom_attributes_settings",
        ["pv_last_updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_attributes_settings_pv_tenant_id"),
        "custom_attributes_settings",
        ["pv_tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_attributes_settings_tenant_group_id_str"),
        "custom_attributes_settings",
        ["tenant_group_id_str"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_attributes_settings_tenant_id_str"),
        "custom_attributes_settings",
        ["tenant_id_str"],
        unique=False,
    )

    # New columns

    op.execute(
        "alter table custom_attributes_configs "
        " rename column is_mandatory to is_mandatory_objective;"
    )

    op.add_column(
        "custom_attributes_configs",
        sa.Column(
            "is_mandatory_keyresult",
            sa.Boolean(),
            nullable=False,
            server_default="false",
        ),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "alter table custom_attributes_configs "
        " rename column is_mandatory_objective to is_mandatory;"
    )
    op.drop_column("custom_attributes_configs", "is_mandatory_keyresult")

    op.drop_index(
        op.f("ix_custom_attributes_settings_tenant_id_str"),
        table_name="custom_attributes_settings",
    )
    op.drop_index(
        op.f("ix_custom_attributes_settings_tenant_group_id_str"),
        table_name="custom_attributes_settings",
    )
    op.drop_index(
        op.f("ix_custom_attributes_settings_pv_tenant_id"),
        table_name="custom_attributes_settings",
    )
    op.drop_index(
        op.f("ix_custom_attributes_settings_pv_last_updated_by"),
        table_name="custom_attributes_settings",
    )
    op.drop_index(
        op.f("ix_custom_attributes_settings_pv_created_by"),
        table_name="custom_attributes_settings",
    )
    op.drop_index(
        op.f("ix_custom_attributes_settings_last_updated_by"),
        table_name="custom_attributes_settings",
    )
    op.drop_index(
        op.f("ix_custom_attributes_settings_created_by"),
        table_name="custom_attributes_settings",
    )
    op.drop_index(
        op.f("ix_custom_attributes_settings_app_last_updated_by"),
        table_name="custom_attributes_settings",
    )
    op.drop_index(
        op.f("ix_custom_attributes_settings_app_created_by"),
        table_name="custom_attributes_settings",
    )
    op.drop_table("custom_attributes_settings")
    # ### end Alembic commands ###
