"""continer type

Revision ID: 20240404153418
Revises: 20240417113648
Create Date: 2024-04-04 15:34:23.124678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20240404153418"
down_revision = "20240403123354"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "work_item_containers", sa.Column("container_type", sa.String(), nullable=True)
    )
    op.add_column("work_items", sa.Column("container_type", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("work_items", "container_type")
    op.drop_column("work_item_containers", "container_type")
    # ### end Alembic commands ###
