"""Adding new cloumn custom_attribute_label to CustomAttributesSettings table

Revision ID: 20240403123354
Revises: 20231122173205
Create Date: 2024-04-03 12:34:03.667947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20240403123354"
down_revision = "20240417113648"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "custom_attributes_settings",
        sa.Column("label", sa.String(), nullable=True),
    )

    op.add_column(
        "custom_attributes_settings",
        sa.Column("tooltip", sa.String(), nullable=True),
    )

    op.add_column(
        "custom_attributes_settings",
        sa.Column("label_hidden", sa.BOOLEAN(), nullable=False, default=False),
    )

    op.create_check_constraint(
        "check_label_length", "custom_attributes_settings", "LENGTH(label) <= 50"
    )

    op.create_check_constraint(
        "check_tooltip_length", "custom_attributes_settings", "LENGTH(tooltip) <= 200"
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_tooltip_length", "custom_attributes_settings")
    op.drop_constraint("check_label_length", "custom_attributes_settings")
    op.drop_column("custom_attributes_settings", "label")
    op.drop_column("custom_attributes_settings", "tooltip")
    op.drop_column("custom_attributes_settings", "label_hidden")

    # ### end Alembic commands ###
