"""new_roll_up_comlumn_for_settings

Revision ID: 20241210102942
Revises: 20241122123220
Create Date: 2024-12-10 10:29:48.423537

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "20241210102942"
down_revision = "20241122123220"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "settings",
        sa.Column("roll_up_progress", sa.BOOLEAN(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "roll_up_progress")


# ### end Alembic commands ###
