"""create user settings

Revision ID: 20240930073728
Revises: 20240802104628
Create Date: 2024-09-30 07:37:30.167284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20240930073728"
down_revision = "20240802104628"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_settings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("app_user_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("pv_tenant_id", sa.String(), nullable=False),
        sa.Column("app_created_by", sa.String(), nullable=True),
        sa.Column("app_last_updated_by", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("last_updated_by", sa.String(), nullable=True),
        sa.Column("pv_created_by", sa.String(), nullable=False),
        sa.Column("pv_last_updated_by", sa.String(), nullable=True),
        sa.Column("tenant_id_str", sa.String(), nullable=True),
        sa.Column("tenant_group_id_str", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_settings_pv_tenant_id"),
        "user_settings",
        ["pv_tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_settings_tenant_group_id_str"),
        "user_settings",
        ["tenant_group_id_str"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_settings_tenant_id_str"),
        "user_settings",
        ["tenant_id_str"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_settings_app_user_id"),
        "user_settings",
        ["app_user_id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_settings_app_user_id"), table_name="user_settings")
    op.drop_index(op.f("ix_user_settings_tenant_id_str"), table_name="user_settings")
    op.drop_index(
        op.f("ix_user_settings_tenant_group_id_str"), table_name="user_settings"
    )
    op.drop_index(op.f("ix_user_settings_pv_tenant_id"), table_name="user_settings")
    op.drop_table("user_settings")
    # ### end Alembic commands ###
