"""color_threshold_settings

Revision ID: 20250423113714
Revises: 20250108163828
Create Date: 2025-04-23 11:37:21.075026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20250423113714"
down_revision = "20250108163828"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "settings",
        sa.Column(
            "is_color_threshold_enabled",
            sa.BOOLEAN(),
            nullable=False,
            server_default="1",
        ),
    )
    op.add_column(
        "settings",
        sa.Column(
            "color_threshold_config",
            sa.JSON(),
            nullable=False,
            server_default=sa.text(
                '\'[{"name":"Red","colorCode":"#F33535","min": 0,"max": 39},{"name":"Amber","colorCode":"#E97407","min": 39,"max": 69},{"name":"Green","colorCode":"#27A444","min": 69,"max": 100}]\'::jsonb'
            ),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "is_color_threshold_enabled")
    op.drop_column("settings", "color_threshold_config")
