"""Adding column rolled_up_progress_percentage to objectives

Revision ID: 20250108163828
Revises: 20241210102942
Create Date: 2025-01-08 16:38:32.951965

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "20250108163828"
down_revision = "20241210102942"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "objectives",
        sa.Column(
            "rolled_up_progress_percentage",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("objectives", "rolled_up_progress_percentage")
