table:
  name: custom_attributes_configs
  schema: public
select_permissions:
  - role: reporting
    permission:
      columns:
        - app_created_by
        - app_last_updated_by
        - ca_config_type
        - created_at
        - created_by
        - deleted_at_epoch
        - id
        - is_archived
        - is_default
        - is_deleted
        - is_keyresult
        - is_mandatory_keyresult
        - is_mandatory_objective
        - is_objective
        - label
        - last_updated_by
        - tenant_group_id_str
        - tenant_id_str
        - tooltip
        - updated_at
        - value
      filter:
        _and:
          - deleted_at_epoch:
              _eq: 0
          - tenant_group_id_str:
              _eq: X-Hasura-Org-Id
      allow_aggregations: true
